// Sample project showcase data for the Anti Gravity portfolio
export const projects = [
  {
    id: '1',
    title: 'Echoes of Silence',
    subtitle: 'Cinematic Short Film',
    category: 'Cinematic',
    client: 'NoIntro Studios',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=600&auto=format&fit=crop',
    description: 'An experimental short film exploring the visual boundaries of silence in dense urban environments. Shot entirely on anamorphic lenses during the twilight hours.',
  },
  {
    id: '2',
    title: 'The Future of Speed',
    subtitle: 'Nike Campaign',
    category: 'Commercial',
    client: 'Nike France',
    year: '2025',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=600&auto=format&fit=crop',
    description: 'A fast-paced, high-energy commercial campaign celebrating the launch of Nike\'s latest running technology. Focuses on raw athleticism and liquid lighting effects.',
  },
  {
    id: '3',
    title: 'Urban Nomads',
    subtitle: 'Vogue Editorial',
    category: 'Lifestyle',
    client: 'Vogue Europe',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600&auto=format&fit=crop',
    description: 'A striking editorial campaign capturing the intersection of high fashion and street culture across European metropolises.',
  },
  {
    id: '4',
    title: 'Above the Ridge',
    subtitle: 'Dolomites Drone Showcase',
    category: 'Aerial',
    client: 'Alpine Tourism',
    year: '2025',
    image: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?q=80&w=600&auto=format&fit=crop',
    description: 'A breathtaking aerial perspective showcasing the rugged peaks and deep valleys of the Dolomites. Emphasizes geometry and natural scale.',
  },
  {
    id: '5',
    title: 'Neon Nights',
    subtitle: 'Tokyo Promo',
    category: 'Lifestyle',
    client: 'Tokyo Tourism',
    year: '2026',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=600&auto=format&fit=crop',
    description: 'A nocturnal exploration of Tokyo\'s iconic neon streets, capturing the vibrant nightlife and cyberpunk-inspired aesthetic of the city.',
  },
];
